### ISSUE TITLE
New language support suggestion : Arabic

### ISSUE THREAD

**Issue by JustE3saR** [zenika-open-source/promote-open-source-project#108]
**I would like to ...**

- [X] offer my help to translate this cheat sheet in another language
- [ ] ask if someone can translate this cheat sheet in another language

**What is the language you would see this cheat sheet translate ?**
Arabic

**Comment by nlepage** [comment]
Hi @JustE3saR 
Glad you want to contribute, let me know if you need any help.

**Comment by JustE3saR** [comment]
I submitted the translation and it was accepted. I will close the issue.
