### ISSUE TITLE
New language support suggestion : Bahasa Indonesia

### ISSUE THREAD

**Issue by HanzCEO** [zenika-open-source/promote-open-source-project#110]
**I would like to ...**

- [x] offer my help to translate this cheat sheet in another language
- [ ] ask if someone can translate this cheat sheet in another language

**What is the language you would see this cheat sheet translate ?**
Bahasa Indonesia

**Comment by nlepage** [comment]
Hi @HanzCEO 
Thank you for your interest.
You may open a pull request if you want.
Let me know if you need any help.
