### ISSUE TITLE
Translations list aligned on the right in all languages

### ISSUE THREAD

**Issue by nlepage** [zenika-open-source/promote-open-source-project#112]
## Problem
The list of translations is aligned on the right on all READMEs.

## Expected
The list of translations should be left-aligned in READMEs written in LTR languages.

## Additional information
This is caused by the first item of the list being written in a RTL language (ie Arabic).

**Comment by Gerappa92** [comment]
Hi, I will take care of it, if you don't mind.

**Comment by nlepage** [comment]
> Hi, I will take care of it, if you don't mind.

No problem, please try to keep the order of the list as it is.
Thanks!

**Comment by Gerappa92** [comment]
Created PR #113.
Review, please.
