### ISSUE TITLE
New language support suggestion : Russian

### ISSUE THREAD

**Issue by lexuzieel** [zenika-open-source/promote-open-source-project#89]
**I would like to ...**

- [x] offer my help to translate this cheat sheet in another language
- [ ] ask if someone can translate this cheat sheet in another language

**What is the language you would see this cheat sheet translate ?**
Add the language you want: Russian

**Comment by tbetous** [comment]
Hi @lexuzieel 👋 

Thank you for opening this issue ! Feel free to open a pull request to add your translation. We will look into it as soon as possible. 👍

**Comment by lexuzieel** [comment]
I am extremely sorry for leaving this hanging for over a year 🙏 Life got in the way and I completely forgot about this.
If anybody else wants to take this for this year's Hacktoberfest I'll gladly yield, otherwise I'll try to finish it during the following month

**Comment by nlepage** [comment]
Hi @lexuzieel 
No problem at all.
A Russian translation has just been merged : https://github.com/zenika-open-source/promote-open-source-project/blob/master/README-ru.md
Feel free to take a look at it and open a pull request if you see any mistakes.
Thanks!
