### ISSUE TITLE
New language support suggestion : Sinhala language

### ISSUE THREAD

**Issue by MasterBrian99** [zenika-open-source/promote-open-source-project#96]
**I would like to ...**

- [x]  offer my help to translate this cheat sheet in another language
- [ ] ask if someone can translate this cheat sheet in another language

**What is the language you would see this cheat sheet translate ?**
Add the language you want

**Comment by tbetous** [comment]
Hi @MasterBrian99  👋

Thank you for opening this issue ! Feel free to open a pull request to add your translation. We will look into it as soon as possible. 👍
